import { NETWORKS } from './NETWORKS';

export const REQUIREMENTS = {
	EMPTY: 'empty',
	EXCLUDE: 'exclude',
	LOCKED: 'locked',
	NORMAL: 'normal',
	STREAM: 'stream'
};

export const SUPPORTED_NETWORKS = {
	ALL: 'all',
	FACEBOOK: NETWORKS.FACEBOOK,
	INSTAGRAM: NETWORKS.INSTAGRAM,
	LINKEDIN: NETWORKS.LINKEDIN,
	YOUTUBE: NETWORKS.YOUTUBE
};